# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo ${{ secrets.DOCKER_USER }} > DOCKER_USER
          echo ${{ secrets.DOCKER_PASS }} > DOCKER_PASS
      - name: Docker login
        run: docker login -u $(cat DOCKER_USER) -p $(cat DOCKER_PASS)
      - name: Docker Build
        run: docker build -t $(cat DOCKER_USER)/bullish-breakouts-ui:latest ./
      - name: Docker push
        run: docker push $(cat DOCKER_USER)/bullish-breakouts-ui:latest

